import os

REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))

IP_RATE_LIMIT = 20
USER_RATE_LIMIT_FREE = 10
USER_RATE_LIMIT_PREMIUM = 100

TIME_WINDOW = 60
